//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerFAQ
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public string Reply { get; set; }
        public int Status { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public System.Guid Createdby { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.Guid> ReplyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Creator { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Modifier { get; set; }
        public virtual Employee Respondents { get; set; }
    }
}
