//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BambooHRHistoryLeaveForm
    {
        public int ID { get; set; }
        public int EmpData_ID { get; set; }
        public string EmpID { get; set; }
        public string FormNo { get; set; }
        public Nullable<System.Guid> PortalLeaveFormID { get; set; }
        public Nullable<int> EmpAbsent_ID { get; set; }
        public Nullable<int> EmpWorkAdjust_ID { get; set; }
        public string AbsentCode { get; set; }
        public System.DateTime BeginTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal AbsentAmount { get; set; }
        public string AbsentUnit { get; set; }
        public int FormStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
