//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BambooHREmployeeMapping
    {
        public int ID { get; set; }
        public string BambooHREmployeeID { get; set; }
        public string BambooHREmail { get; set; }
        public string BambooHREmployeeName { get; set; }
        public Nullable<System.Guid> PortalEmployeeID { get; set; }
        public Nullable<int> EmpData_ID { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string DefaultAgentEmpID { get; set; }
        public Nullable<System.Guid> DefaultAgentPortalEmployeeID { get; set; }
        public string BambooHRUserID { get; set; }
        public string BambooHRUserFirstName { get; set; }
        public string BambooHRUserLastName { get; set; }
        public string BambooHRUserEmail { get; set; }
        public string BambooHRUserStatus { get; set; }
        public string BambooHRUserLastLogin { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
