//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BambooHRTimeOffType
    {
        public int ID { get; set; }
        public string BambooHR_TimeOffTypeID { get; set; }
        public string BambooHR_TimeOffTypeName { get; set; }
        public string BambooHR_TimeOffTypeUnit { get; set; }
        public string HRM_AbsentCode { get; set; }
        public int HRM_AbsentID { get; set; }
        public string HRM_AbsentName { get; set; }
        public string HRM_AbsentNameEN { get; set; }
        public string HRM_AbsentUnit { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
