//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BambooHRLeaveFormRecord
    {
        public int ID { get; set; }
        public Nullable<System.Guid> PortalLeaveFormID { get; set; }
        public string BambooHRTimeOffID { get; set; }
        public Nullable<int> EmpData_ID { get; set; }
        public string EmpID { get; set; }
        public string BambooHREmployeeID { get; set; }
        public Nullable<System.Guid> PortalEmployeeID { get; set; }
        public string FormNo { get; set; }
        public string BambooHRStatus { get; set; }
        public int FormStatus { get; set; }
        public string PortalAbsentCode { get; set; }
        public Nullable<System.DateTime> PortalStartTime { get; set; }
        public Nullable<System.DateTime> PortalEndTime { get; set; }
        public Nullable<decimal> PortalLeaveAmount { get; set; }
        public string PortalAbsentUnit { get; set; }
        public string PortalLeaveReason { get; set; }
        public string AgentEmpID { get; set; }
        public Nullable<System.DateTime> BambooHRStartDate { get; set; }
        public Nullable<System.DateTime> BambooHREndDate { get; set; }
        public Nullable<decimal> BambooHRLeaveAmount { get; set; }
        public string BambooHRLeaveReason { get; set; }
        public string BambooHRManagerNote { get; set; }
        public Nullable<System.DateTime> BambooHRConfirmedStartTime { get; set; }
        public Nullable<System.DateTime> BambooHRConfirmedEndTime { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateFrom { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateFrom { get; set; }
    
        public virtual LeaveForm LeaveForm { get; set; }
    }
}
