//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BambooHRMailNotificationSetting
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public bool Enabled { get; set; }
        public int RcptType { get; set; }
        public int CCType { get; set; }
        public string CustomRcpt { get; set; }
        public string CustomCC { get; set; }
        public string DefaultSubject { get; set; }
        public string DefaultContent { get; set; }
        public bool IsHTML { get; set; }
    }
}
