//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasualForm
    {
        public System.Guid ID { get; set; }
        public string EmployeeNO { get; set; }
        public int EmpData_ID { get; set; }
        public string EmpName { get; set; }
        public int Dept_ID { get; set; }
        public string Dept_Code { get; set; }
        public string Dept_Name { get; set; }
        public int Cost_ID { get; set; }
        public string Cost_Code { get; set; }
        public string Cost_Name { get; set; }
        public System.DateTime ExcuteDate { get; set; }
        public int Class_ID { get; set; }
        public string Class_Code { get; set; }
        public string Class_Name { get; set; }
        public string DefaultStartTime { get; set; }
        public string DefaultEndTime { get; set; }
        public double DefaultWorkHours { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public string SalaryUnit { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> Allowance { get; set; }
        public string CardNo { get; set; }
        public Nullable<bool> CardKeep { get; set; }
        public Nullable<bool> CashFlag { get; set; }
        public string CasualFormNo { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateEmployeeNO { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateEmployeeNO { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<double> DaySalary { get; set; }
        public Nullable<double> DiningHours { get; set; }
        public string Status { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
