//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptCost
    {
        public System.Guid ID { get; set; }
        public int Dept_id { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public int Cost_id { get; set; }
        public string CostCode { get; set; }
        public string CostName { get; set; }
        public System.Guid CompanyID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
