//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EffectiveDate
    {
        public System.Guid ID { get; set; }
        public int Function_Type { get; set; }
        public Nullable<System.Guid> Function_ID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<System.Guid> Change_ID { get; set; }
        public Nullable<System.DateTime> Change_Date { get; set; }
        public string Change_Type { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedUser { get; set; }
    }
}
