//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpALSchedule
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public int Year { get; set; }
        public double S01 { get; set; }
        public double S02 { get; set; }
        public double S03 { get; set; }
        public double S04 { get; set; }
        public double S05 { get; set; }
        public double S06 { get; set; }
        public double S07 { get; set; }
        public double S08 { get; set; }
        public double S09 { get; set; }
        public double S10 { get; set; }
        public double S11 { get; set; }
        public double S12 { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public double D01 { get; set; }
        public double D02 { get; set; }
        public double D03 { get; set; }
        public double D04 { get; set; }
        public double D05 { get; set; }
        public double D06 { get; set; }
        public double D07 { get; set; }
        public double D08 { get; set; }
        public double D09 { get; set; }
        public double D10 { get; set; }
        public double D11 { get; set; }
        public double D12 { get; set; }
    
        public virtual Company Companys { get; set; }
        public virtual Department Departments { get; set; }
        public virtual Employee Employees { get; set; }
    }
}
