//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ManageDepartments = new HashSet<Department>();
            this.ReportFrom = new HashSet<Employee>();
            this.ReadToday = new HashSet<ReadToday>();
            this.ReadToday1 = new HashSet<ReadToday>();
            this.Personnelspecification = new HashSet<Personnelspecification>();
            this.Personnelspecification1 = new HashSet<Personnelspecification>();
            this.EmployeeBenefits = new HashSet<EmployeeBenefits>();
            this.EmployeeBenefits1 = new HashSet<EmployeeBenefits>();
            this.PatchCardCancel = new HashSet<PatchCardCancel>();
            this.PatchCardCancel1 = new HashSet<PatchCardCancel>();
            this.PatchCardCancel2 = new HashSet<PatchCardCancel>();
            this.Vacancies = new HashSet<Vacancies>();
            this.Vacancies1 = new HashSet<Vacancies>();
            this.AnswerVacancies = new HashSet<AnswerVacancies>();
            this.AnswerVacancies1 = new HashSet<AnswerVacancies>();
            this.AnswerVacancies2 = new HashSet<AnswerVacancies>();
            this.AnswerVacancies3 = new HashSet<AnswerVacancies>();

            this.BambooHREmployeeMappings = new HashSet<BambooHREmployeeMapping>();

            this.EmpALSchedule = new HashSet<EmpALSchedule>();
        }
    
        public System.Guid ID { get; set; }
        public string EmployeeNO { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEnglishName { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public Nullable<System.Guid> ReportToID { get; set; }
        public short Gender { get; set; }
        public string CellphoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime ArriveDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> PasswordExpiredDate { get; set; }
        public System.Guid RoleID { get; set; }
        public bool TopExecutive { get; set; }
        public System.Guid SignDepartmentID { get; set; }
        public string Address { get; set; }
        public string RegisterAddress { get; set; }
        public string EmployeeType { get; set; }
        public string RegisterTelephoneNumber { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyTelephoneNumber { get; set; }
        public string EmergencyRelation { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> EmployeesLevel { get; set; }
        public int PasswordFailedCount { get; set; }
        public bool PasswordLockStatus { get; set; }
        public Nullable<System.DateTime> PasswordLockDate { get; set; }
        public string SalaryPasswordHash { get; set; }
        public string FirstModifiedFlag { get; set; }
        public string DesignatedPerson { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> ManageDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> ReportFrom { get; set; }
        public virtual Employee ReportTo { get; set; }
        public virtual Role Role { get; set; }
        public virtual Department SignDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadToday> ReadToday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadToday> ReadToday1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnelspecification> Personnelspecification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personnelspecification> Personnelspecification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeBenefits> EmployeeBenefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeBenefits> EmployeeBenefits1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatchCardCancel> PatchCardCancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatchCardCancel> PatchCardCancel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatchCardCancel> PatchCardCancel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancies> Vacancies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancies> Vacancies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerVacancies> AnswerVacancies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerVacancies> AnswerVacancies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerVacancies> AnswerVacancies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerVacancies> AnswerVacancies3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BambooHREmployeeMapping> BambooHREmployeeMappings { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpALSchedule> EmpALSchedule { get; set; }
    }
}
