//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewHRPortalEntities : DbContext
    {
        public NewHRPortalEntities()
            : base("name=NewHRPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Company> Companys { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<RoleMenuMap> RoleMenuMaps { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<MailAccount> MailAccounts { get; set; }
        public virtual DbSet<MailMessage> MailMessages { get; set; }
        public virtual DbSet<DownloadFile> DownloadFiles { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FAQType> FAQTypes { get; set; }
        public virtual DbSet<PatchCardForm> PatchCardForms { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LeaveForm> LeaveForms { get; set; }
        public virtual DbSet<OverTimeForm> OverTimeForms { get; set; }
        public virtual DbSet<SerialControl> SerialControls { get; set; }
        public virtual DbSet<AnswerFAQ> AnswerFAQs { get; set; }
        public virtual DbSet<OptionGroup> OptionGroups { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<AnnouncementFile> AnnouncementFiles { get; set; }
        public virtual DbSet<LeaveCancel> LeaveCancels { get; set; }
        public virtual DbSet<OverTimeCancel> OverTimeCancels { get; set; }
        public virtual DbSet<CasualForm> CasualForms { get; set; }
        public virtual DbSet<DeptCost> DeptCosts { get; set; }
        public virtual DbSet<CasualCycle> CasualCycles { get; set; }
        public virtual DbSet<WebLinkList> WebLinkLists { get; set; }
        public virtual DbSet<FormSetting> FormSettings { get; set; }
        public virtual DbSet<ReadToday> ReadToday { get; set; }
        public virtual DbSet<ReadTodayFiles> ReadTodayFiles { get; set; }
        public virtual DbSet<Personnelspecification> Personnelspecification { get; set; }
        public virtual DbSet<PersonnelspecificationFiles> PersonnelspecificationFiles { get; set; }
        public virtual DbSet<WebLinkListFEDS> WebLinkListFEDS { get; set; }
        public virtual DbSet<SignoffAgents> SignoffAgents { get; set; }
        public virtual DbSet<EmployeeBenefits> EmployeeBenefits { get; set; }
        public virtual DbSet<EmployeeBenefitsFiles> EmployeeBenefitsFiles { get; set; }
        public virtual DbSet<CasualFormLog> CasualFormLog { get; set; }
        public virtual DbSet<EffectiveDate> EffectiveDate { get; set; }
        public virtual DbSet<PatchCardCancel> PatchCardCancel { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
        public virtual DbSet<VacanciesType> VacanciesType { get; set; }
        public virtual DbSet<AnswerVacancies> AnswerVacancies { get; set; }
        public virtual DbSet<PersonalSettings> PersonalSettings { get; set; }
        public virtual DbSet<BambooHRHistoryLeaveForm> BambooHRHistoryLeaveForm { get; set; }
        public virtual DbSet<BambooHRTimeOffType> BambooHRTimeOffTypes { get; set; }
        public virtual DbSet<BambooHREmployeeMapping> BambooHREmployeeMappings { get; set; }
        public virtual DbSet<BambooHRMailNotificationSetting> BambooHRMailNotificationSettings { get; set; }
        public virtual DbSet<BambooHRLeaveFormRecordLog> BambooHRLeaveFormRecordLogs { get; set; }
        public virtual DbSet<BambooHRLeaveFormRecord> BambooHRLeaveFormRecords { get; set; }
        public virtual DbSet<EmpALSchedule> EmpALSchedule { get; set; }
    }
}
