//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveForm()
        {
            this.LeaveCancels = new HashSet<LeaveCancel>();
            this.BambooHRLeaveFormRecords = new HashSet<BambooHRLeaveFormRecord>();
        }
    
        public System.Guid ID { get; set; }
        public string FormNo { get; set; }
        public int Status { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public string AbsentCode { get; set; }
        public decimal AbsentAmount { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal LeaveAmount { get; set; }
        public decimal AfterAmount { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<System.Guid> AgentID { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public System.Guid Createdby { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public bool IsAbroad { get; set; }
        public string AbsentUnit { get; set; }
        public string FileFormat { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Agent { get; set; }
        public virtual Employee Creator { get; set; }
        public virtual Employee Deleter { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Modifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCancel> LeaveCancels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BambooHRLeaveFormRecord> BambooHRLeaveFormRecords { get; set; }
    }
}
