//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMessage
    {
        public System.Guid ID { get; set; }
        public System.Guid FromAccountID { get; set; }
        public string Rcpt { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public bool HadSend { get; set; }
        public Nullable<System.DateTime> SendTimeStamp { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ErrorTimeStamp { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual MailAccount MailAccount { get; set; }
    }
}
