//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatchCardCancel
    {
        public System.Guid ID { get; set; }
        public string FormNo { get; set; }
        public int Status { get; set; }
        public string CancelReason { get; set; }
        public System.Guid Createdby { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public System.Guid PatchCardFormID { get; set; }
    
        public virtual Employee Employees { get; set; }
        public virtual Employee Employees1 { get; set; }
        public virtual Employee Employees2 { get; set; }
        public virtual PatchCardForm PatchCardForm { get; set; }
    }
}
