//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenuMap
    {
        public System.Guid ID { get; set; }
        public System.Guid Role_ID { get; set; }
        public System.Guid Menu_ID { get; set; }
        public string MenuParams { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
    }
}
