//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLinkList
    {
        public System.Guid ID { get; set; }
        public string WebName { get; set; }
        public string WebLink { get; set; }
        public bool IsUsed { get; set; }
        public System.Guid Createdby { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.Guid> Deletedby { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<int> Number { get; set; }
        public bool IsDeleted { get; set; }
    }
}
