//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewHRPortalEntitiesDDMC_PFA : DbContext
    {
        public NewHRPortalEntitiesDDMC_PFA()
            : base("name=NewHRPortalEntitiesDDMC_PFA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PfaDept> PfaDept { get; set; }
        public virtual DbSet<PfaDeptEmp> PfaDeptEmp { get; set; }
        public virtual DbSet<PfaOption> PfaOption { get; set; }
        public virtual DbSet<PfaOptionGroup> PfaOptionGroup { get; set; }
        public virtual DbSet<PfaDepartment> Departments { get; set; }
        public virtual DbSet<PfaEmployee> Employees { get; set; }
        public virtual DbSet<PfaRole> Roles { get; set; }
        public virtual DbSet<PfaCompany> Companys { get; set; }
        public virtual DbSet<PfaMenu> Menus { get; set; }
        public virtual DbSet<PfaRoleMenuMaps> RoleMenuMaps { get; set; }
        public virtual DbSet<PfaSystemLog> SystemLog { get; set; }
        public virtual DbSet<PfaSystemSetting> SystemSetting { get; set; }
        public virtual DbSet<PfaMailAccount> MailAccount { get; set; }
        public virtual DbSet<PfaOrg> PfaOrg { get; set; }
        public virtual DbSet<PfaOrgDept> PfaOrgDept { get; set; }
        public virtual DbSet<PfaPerformance> PfaPerformance { get; set; }
        public virtual DbSet<PfaEmpType> PfaEmpType { get; set; }
        public virtual DbSet<PfaEmpTypeTargets> PfaEmpTypeTargets { get; set; }
        public virtual DbSet<PfaSignFlow> PfaSignFlow { get; set; }
        public virtual DbSet<PfaTargets> PfaTargets { get; set; }
        public virtual DbSet<PfaAbility> PfaAbility { get; set; }
        public virtual DbSet<PfaAbilityDetail> PfaAbilityDetail { get; set; }
        public virtual DbSet<PfaRatioJobTitle> PfaRatioJobTitle { get; set; }
        public virtual DbSet<PfaSignProcess> PfaSignProcess { get; set; }
        public virtual DbSet<PfaSignRecord> PfaSignRecord { get; set; }
        public virtual DbSet<PfaCycleRation> PfaCycleRation { get; set; }
        public virtual DbSet<PfaCycleRationDetail> PfaCycleRationDetail { get; set; }
        public virtual DbSet<PfaEmpAbility> PfaEmpAbility { get; set; }
        public virtual DbSet<PfaEmpAbilityDetail> PfaEmpAbilityDetail { get; set; }
        public virtual DbSet<PfaSignerList> PfaSignerList { get; set; }
        public virtual DbSet<PfaMailMessage> PfaMailMessage { get; set; }
        public virtual DbSet<PfaMailMessageMain> MailMessage { get; set; }
        public virtual DbSet<PfaIndicator> PfaIndicator { get; set; }
        public virtual DbSet<PfaIndicatorDetail> PfaIndicatorDetail { get; set; }
        public virtual DbSet<PfaEmpIndicator> PfaEmpIndicator { get; set; }
        public virtual DbSet<PfaCycle> PfaCycle { get; set; }
        public virtual DbSet<PfaEmpTraining> PfaEmpTraining { get; set; }
        public virtual DbSet<PfaSignUpload> PfaSignUpload { get; set; }
        public virtual DbSet<PfaCycleEmp> PfaCycleEmp { get; set; }
    }
}
