//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaAbilityDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid PfaAbilityID { get; set; }
        public string PfaAbilityKey { get; set; }
        public Nullable<int> UpperLimit { get; set; }
        public Nullable<int> LowerLimit { get; set; }
        public Nullable<int> Ordering { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual PfaAbility PfaAbility { get; set; }
    }
}
