//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaCycleEmp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaCycleEmp()
        {
            this.PfaEmpAbility = new HashSet<PfaEmpAbility>();
            this.PfaEmpIndicator = new HashSet<PfaEmpIndicator>();
            this.PfaEmpTraining = new HashSet<PfaEmpTraining>();
            this.PfaSignProcess = new HashSet<PfaSignProcess>();
            this.PfaSignRecord = new HashSet<PfaSignRecord>();
            this.PfaSignUpload = new HashSet<PfaSignUpload>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PfaCycleID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid PfaDeptID { get; set; }
        public Nullable<System.Guid> PfaOrgID { get; set; }
        public Nullable<System.Guid> HireID { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public Nullable<System.Guid> JobFunctionID { get; set; }
        public Nullable<System.Guid> GradeID { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public string Education { get; set; }
        public string SchoolName { get; set; }
        public string DeptDescription { get; set; }
        public bool Degree { get; set; }
        public Nullable<double> PersonalLeave { get; set; }
        public Nullable<double> SickLeave { get; set; }
        public Nullable<double> LateLE { get; set; }
        public Nullable<double> AWL { get; set; }
        public Nullable<double> Salary01 { get; set; }
        public Nullable<double> Salary02 { get; set; }
        public Nullable<double> Salary03 { get; set; }
        public Nullable<double> Salary04 { get; set; }
        public Nullable<double> Salary05 { get; set; }
        public Nullable<double> Salary06 { get; set; }
        public Nullable<double> FullSalary { get; set; }
        public string Performance1 { get; set; }
        public string Performance2 { get; set; }
        public string Performance3 { get; set; }
        public Nullable<System.Guid> SignTypeID { get; set; }
        public Nullable<System.Guid> PfaEmpTypeID { get; set; }
        public bool IsAgent { get; set; }
        public bool IsRatio { get; set; }
        public string Status { get; set; }
        public Nullable<double> SelfIndicator { get; set; }
        public Nullable<double> ManagerIndicator { get; set; }
        public Nullable<double> ManagerAbility { get; set; }
        public Nullable<double> PfaSelfScore { get; set; }
        public Nullable<double> PfaFirstScore { get; set; }
        public Nullable<System.Guid> FirstPerformance_ID { get; set; }
        public Nullable<double> PfaLastScore { get; set; }
        public Nullable<System.Guid> LastPerformance_ID { get; set; }
        public Nullable<double> PfaFinalScore { get; set; }
        public Nullable<System.Guid> FinalPerformance_ID { get; set; }
        public string SelfAppraisal { get; set; }
        public string FirstAppraisal { get; set; }
        public Nullable<System.Guid> PastPerformance { get; set; }
        public Nullable<System.Guid> NowPerformance { get; set; }
        public Nullable<System.Guid> Development { get; set; }
        public string LastAppraisal { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string FinalAppraisal { get; set; }
    
        public virtual PfaOption PfaOption { get; set; }
        public virtual PfaDept PfaDept { get; set; }
        public virtual PfaEmpType PfaEmpType { get; set; }
        public virtual PfaOption PfaOption1 { get; set; }
        public virtual PfaOption PfaOption2 { get; set; }
        public virtual PfaOption PfaOption3 { get; set; }
        public virtual PfaOption PfaOption4 { get; set; }
        public virtual PfaOption PfaOption5 { get; set; }
        public virtual PfaOrg PfaOrg { get; set; }
        public virtual PfaPerformance PfaPerformance { get; set; }
        public virtual PfaPerformance PfaPerformance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmpAbility> PfaEmpAbility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmpIndicator> PfaEmpIndicator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmpTraining> PfaEmpTraining { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignProcess> PfaSignProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignRecord> PfaSignRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignUpload> PfaSignUpload { get; set; }
        public virtual PfaEmployee Employees { get; set; }
    }
}
