//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaCycleRationDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid PfaCycleRationID { get; set; }
        public System.Guid PfaPerformanceID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Ordering { get; set; }
        public string Performance { get; set; }
        public string band { get; set; }
        public Nullable<int> Rates { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> ScoresStart { get; set; }
        public Nullable<decimal> ScoresEnd { get; set; }
        public Nullable<decimal> BudgetTotal { get; set; }
        public Nullable<int> Staffing { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<int> FirstFinal { get; set; }
        public Nullable<int> SecondFinal { get; set; }
        public Nullable<decimal> FinalRation { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ThirdFinal { get; set; }
    
        public virtual PfaCycleRation PfaCycleRation { get; set; }
        public virtual PfaPerformance PfaPerformance { get; set; }
    }
}
