//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaCycle()
        {
            this.PfaCycleRation = new HashSet<PfaCycleRation>();
            this.PfaMailMessage = new HashSet<PfaMailMessage>();
            this.PfaSignerList = new HashSet<PfaSignerList>();
        }
    
        public System.Guid ID { get; set; }
        public string PfaFormNo { get; set; }
        public string PfaYear { get; set; }
        public Nullable<System.DateTime> ServeBasedate { get; set; }
        public Nullable<System.DateTime> DutyBeginDate { get; set; }
        public Nullable<System.DateTime> DutyEndDate { get; set; }
        public string Desription { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.DateTime> AssumeBasedate { get; set; }
    
        public virtual PfaCompany Companys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleRation> PfaCycleRation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaMailMessage> PfaMailMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignerList> PfaSignerList { get; set; }
    }
}
