//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaCycleRation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaCycleRation()
        {
            this.PfaCycleRationDetail = new HashSet<PfaCycleRationDetail>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PfaCycleID { get; set; }
        public System.Guid PfaOrgID { get; set; }
        public Nullable<int> OrgTotal { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public Nullable<int> SelfFinal { get; set; }
        public Nullable<int> FirstFinal { get; set; }
        public Nullable<int> SecondFinal { get; set; }
        public Nullable<decimal> FinalRation { get; set; }
        public bool IsRation { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ThirdFinal { get; set; }
    
        public virtual PfaOrg PfaOrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleRationDetail> PfaCycleRationDetail { get; set; }
        public virtual PfaCycle PfaCycle { get; set; }
    }
}
