//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaDept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaDept()
        {
            this.PfaDeptEmp = new HashSet<PfaDeptEmp>();
            this.PfaOrgDept = new HashSet<PfaOrgDept>();
            this.PfaSignFlow = new HashSet<PfaSignFlow>();
            this.PfaCycleEmp = new HashSet<PfaCycleEmp>();
        }
    
        public System.Guid ID { get; set; }
        public string PfaDeptCode { get; set; }
        public string PfaDeptName { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> ParentDepartmentID { get; set; }
        public Nullable<System.Guid> SignParentID { get; set; }
        public Nullable<System.Guid> ManagerID { get; set; }
        public Nullable<System.Guid> SignManagerID { get; set; }
        public System.Guid DeptClassID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool OnlyForSign { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDeptEmp> PfaDeptEmp { get; set; }
        public virtual PfaCompany Companys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaOrgDept> PfaOrgDept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignFlow> PfaSignFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp { get; set; }
    }
}
