//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaDepartment()
        {
            this.Employees = new HashSet<PfaEmployee>();
            this.Departments1 = new HashSet<PfaDepartment>();
            this.Departments11 = new HashSet<PfaDepartment>();
            this.Employees3 = new HashSet<PfaEmployee>();
        }
    
        public System.Guid ID { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentEnglishName { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> ParentDepartmentID { get; set; }
        public Nullable<System.Guid> SignParentID { get; set; }
        public Nullable<System.Guid> ManagerId { get; set; }
        public Nullable<System.Guid> SignManagerId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool OnlyForSign { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> DepartmentsLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmployee> Employees { get; set; }
        public virtual PfaEmployee Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDepartment> Departments1 { get; set; }
        public virtual PfaDepartment Departments2 { get; set; }
        public virtual PfaEmployee Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDepartment> Departments11 { get; set; }
        public virtual PfaDepartment Departments3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmployee> Employees3 { get; set; }
        public virtual PfaCompany Companys { get; set; }
    }
}
