//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaEmployee()
        {
            this.Departments1 = new HashSet<PfaDepartment>();
            this.Departments2 = new HashSet<PfaDepartment>();
            this.Employees1 = new HashSet<PfaEmployee>();
            this.PfaDeptEmp = new HashSet<PfaDeptEmp>();
            this.SystemLog = new HashSet<PfaSystemLog>();
            this.PfaOrg = new HashSet<PfaOrg>();
            this.PfaSignFlow = new HashSet<PfaSignFlow>();
            this.PfaSignProcess = new HashSet<PfaSignProcess>();
            this.PfaSignProcess1 = new HashSet<PfaSignProcess>();
            this.PfaSignProcess2 = new HashSet<PfaSignProcess>();
            this.PfaSignRecord = new HashSet<PfaSignRecord>();
            this.PfaSignRecord1 = new HashSet<PfaSignRecord>();
            this.PfaSignRecord2 = new HashSet<PfaSignRecord>();
            this.PfaSignerList = new HashSet<PfaSignerList>();
            this.PfaMailMessage = new HashSet<PfaMailMessage>();
            this.PfaCycleEmp = new HashSet<PfaCycleEmp>();
        }
    
        public System.Guid ID { get; set; }
        public string EmployeeNO { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEnglishName { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public System.Guid SignDepartmentID { get; set; }
        public Nullable<System.Guid> ReportToID { get; set; }
        public short Gender { get; set; }
        public string CellphoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string EmployeeType { get; set; }
        public string Address { get; set; }
        public string RegisterAddress { get; set; }
        public string RegisterTelephoneNumber { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyRelation { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyTelephoneNumber { get; set; }
        public System.DateTime ArriveDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> PasswordExpiredDate { get; set; }
        public System.Guid RoleID { get; set; }
        public bool TopExecutive { get; set; }
        public Nullable<int> EmployeesLevel { get; set; }
        public int PasswordFailedCount { get; set; }
        public bool PasswordLockStatus { get; set; }
        public Nullable<System.DateTime> PasswordLockDate { get; set; }
        public string SalaryPasswordHash { get; set; }
        public string FirstModifiedFlag { get; set; }
        public string PersonalEmail { get; set; }
        public string DesignatedPerson { get; set; }
    
        public virtual PfaDepartment Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDepartment> Departments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDepartment> Departments2 { get; set; }
        public virtual PfaDepartment SignDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaEmployee> Employees1 { get; set; }
        public virtual PfaEmployee Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaDeptEmp> PfaDeptEmp { get; set; }
        public virtual PfaRole Role { get; set; }
        public virtual PfaCompany Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSystemLog> SystemLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaOrg> PfaOrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignFlow> PfaSignFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignProcess> PfaSignProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignProcess> PfaSignProcess1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignProcess> PfaSignProcess2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignRecord> PfaSignRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignRecord> PfaSignRecord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignRecord> PfaSignRecord2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignerList> PfaSignerList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaMailMessage> PfaMailMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp { get; set; }
    }
}
