//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaMenu()
        {
            this.Menus1 = new HashSet<PfaMenu>();
            this.RoleMenuMaps = new HashSet<PfaRoleMenuMaps>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Link { get; set; }
        public int Type { get; set; }
        public int Ordering { get; set; }
        public Nullable<System.Guid> Parent_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaMenu> Menus1 { get; set; }
        public virtual PfaMenu Menus2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaRoleMenuMaps> RoleMenuMaps { get; set; }
    }
}
