//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaMailAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaMailAccount()
        {
            this.PfaMailMessage = new HashSet<PfaMailMessage>();
            this.MailMessage = new HashSet<PfaMailMessageMain>();
        }
    
        public System.Guid ID { get; set; }
        public string MailAddress { get; set; }
        public string SmtpServer { get; set; }
        public int SmtpServerPort { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public bool SslEnabled { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaMailMessage> PfaMailMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaMailMessageMain> MailMessage { get; set; }
    }
}
