//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaOrg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaOrg()
        {
            this.PfaOrgDept = new HashSet<PfaOrgDept>();
            this.PfaCycleRation = new HashSet<PfaCycleRation>();
            this.PfaCycleEmp = new HashSet<PfaCycleEmp>();
        }
    
        public System.Guid ID { get; set; }
        public string PfaOrgCode { get; set; }
        public string PfaOrgName { get; set; }
        public Nullable<System.Guid> OrgManagerId { get; set; }
        public Nullable<int> Ordering { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual PfaCompany Companys { get; set; }
        public virtual PfaEmployee Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaOrgDept> PfaOrgDept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleRation> PfaCycleRation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp { get; set; }
    }
}
