//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaOption()
        {
            this.PfaRatioJobTitle = new HashSet<PfaRatioJobTitle>();
            this.PfaSignProcess = new HashSet<PfaSignProcess>();
            this.PfaSignRecord = new HashSet<PfaSignRecord>();
            this.PfaCycleEmp = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp1 = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp2 = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp3 = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp4 = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp5 = new HashSet<PfaCycleEmp>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PfaOptionGroupID { get; set; }
        public string OptionCode { get; set; }
        public string OptionName { get; set; }
        public int Ordering { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual PfaOptionGroup PfaOptionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaRatioJobTitle> PfaRatioJobTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignProcess> PfaSignProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignRecord> PfaSignRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp5 { get; set; }
    }
}
