//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaPerformance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaPerformance()
        {
            this.PfaCycleRationDetail = new HashSet<PfaCycleRationDetail>();
            this.PfaCycleEmp = new HashSet<PfaCycleEmp>();
            this.PfaCycleEmp1 = new HashSet<PfaCycleEmp>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<int> Ordering { get; set; }
        public string Performance { get; set; }
        public string band { get; set; }
        public Nullable<int> Rates { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> ScoresStart { get; set; }
        public Nullable<decimal> ScoresEnd { get; set; }
        public System.Guid CompanyID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleRationDetail> PfaCycleRationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaCycleEmp> PfaCycleEmp1 { get; set; }
    }
}
