//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaSignProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PfaSignProcess()
        {
            this.PfaSignUpload = new HashSet<PfaSignUpload>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PfaCycleEmpID { get; set; }
        public int SignStep { get; set; }
        public System.Guid SignLevelID { get; set; }
        public bool IsSelfEvaluation { get; set; }
        public bool IsFirstEvaluation { get; set; }
        public bool IsSecondEvaluation { get; set; }
        public bool IsUpload { get; set; }
        public Nullable<System.Guid> PfaEmpTypeID { get; set; }
        public bool IsAgent { get; set; }
        public bool IsRatio { get; set; }
        public System.Guid OrgSignEmpID { get; set; }
        public System.Guid PreSignEmpID { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> SignEmpID { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public string Assessment { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsThirdEvaluation { get; set; }
    
        public virtual PfaEmployee Employees { get; set; }
        public virtual PfaEmployee Employees1 { get; set; }
        public virtual PfaEmployee Employees2 { get; set; }
        public virtual PfaEmpType PfaEmpType { get; set; }
        public virtual PfaOption PfaOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PfaSignUpload> PfaSignUpload { get; set; }
        public virtual PfaCycleEmp PfaCycleEmp { get; set; }
    }
}
