//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaSignerList
    {
        public System.Guid ID { get; set; }
        public System.Guid PfaCycleID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string SignType { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> SecondDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public bool IsMeat { get; set; }
    
        public virtual PfaEmployee Employees { get; set; }
        public virtual PfaCycle PfaCycle { get; set; }
    }
}
