//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal.DBEntities.DDMC_PFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PfaSignFlow
    {
        public System.Guid ID { get; set; }
        public System.Guid SignTypeID { get; set; }
        public int SignStep { get; set; }
        public System.Guid SignLevelID { get; set; }
        public Nullable<System.Guid> DeptClassID { get; set; }
        public Nullable<System.Guid> EmployeesID { get; set; }
        public Nullable<System.Guid> DepartmentsID { get; set; }
        public bool IsSelfEvaluation { get; set; }
        public bool IsFirstEvaluation { get; set; }
        public bool IsSecondEvaluation { get; set; }
        public bool IsUpload { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsThirdEvaluation { get; set; }
    
        public virtual PfaEmployee Employees { get; set; }
        public virtual PfaDept PfaDept { get; set; }
    }
}
