//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoungCloud.SignFlow.Databases.UnitOfWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignFlowRec
    {
        public string ID { get; set; }
        public string FormNumber { get; set; }
        public string FormType { get; set; }
        public string FormLevelID { get; set; }
        public string SignOrder { get; set; }
        public string SignStatus { get; set; }
        public string SignType { get; set; }
        public string SignerID { get; set; }
        public string ActSignerID { get; set; }
        public string Instruction { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string IsUsed { get; set; }
        public decimal GroupId { get; set; }
        public string CUser { get; set; }
        public System.DateTime CDate { get; set; }
        public string MUser { get; set; }
        public System.DateTime MDate { get; set; }
        public string SenderID { get; set; }
        public string SignCompanyID { get; set; }
        public string SenderCompanyID { get; set; }
        public string OrgSignerID { get; set; }
    }
}
