//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoungCloud.SignFlow.Databases.UnitOfWorks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignFlowEntities : DbContext
    {
        public SignFlowEntities()
            : base("name=SignFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SignFlowAssignDept> SignFlowAssignDept { get; set; }
        public virtual DbSet<SignFlowDesign> SignFlowDesign { get; set; }
        public virtual DbSet<SignFlowFormLevel> SignFlowFormLevel { get; set; }
        public virtual DbSet<SignFlowLevel> SignFlowLevel { get; set; }
        public virtual DbSet<SystemSetting> SystemSetting { get; set; }
        public virtual DbSet<SignFlowConditions> SignFlowConditions { get; set; }
        public virtual DbSet<SignFlowRec> SignFlowRec { get; set; }
    }
}
