//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoungCloud.SignFlow.Databases.UnitOfWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignFlowConditions
    {
        public System.Guid ID { get; set; }
        public string DesignID { get; set; }
        public string LevelID { get; set; }
        public string ConditionType { get; set; }
        public string Parameters { get; set; }
        public string IsUsed { get; set; }
        public string AbsentCode { get; set; }
    }
}
